{% set version = "1.4.3" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: 5955093bbd4dd2e9403c5afaf57324ad8b04f16886512a3ee6ef828956481c57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - babel >=2.9.0
  run:
    - python >=3.7
    - click >=7.0
    - colorama >=0.4
    - jinja2 >=2.11.1
    - markdown >=3.2.1,<3.4
    - pyyaml >=5.1
    - watchdog >=2.0
    - ghp-import >=1.0
    - pyyaml-env-tag >=0.1
    - packaging >=20.5
    - mergedeep >=1.3.4
    - importlib-metadata >=4.3
    - typing-extensions >=3.10
    - packaging >=20.5
    - mergedeep >=1.3.4
  run_constrained:
    - babel >=2.9.0

test:
  requires:
    - pip
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.contrib
    - mkdocs.contrib.search
    - mkdocs.structure
    - mkdocs.tests
    - mkdocs.tests.config
    - mkdocs.tests.structure
    - mkdocs.tests.utils
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - pip check
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Project documentation with Markdown

extra:
  recipe-maintainers:
    - dhirschfeld
    - ocefpaf
