{% set version = "1.6.1" %}

package:
  name: mkdocs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mkdocs/mkdocs-{{ version }}.tar.gz
  sha256: 7b432f01d928c084353ab39c57282f29f92136665bdd6abf7c1ec8d822ef86f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mkdocs = mkdocs.__main__:cli

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    # not really needed but the build crashes bc batch expects it
    - babel >=2.9.0
  run:
    - python >=3.8
    - click >=7.0
    - colorama >=0.4
    - ghp-import >=1.0
    - importlib-metadata >=4.4
    - jinja2 >=2.11.1
    - markdown >=3.3.6
    - markupsafe >=2.0.1
    - mergedeep >=1.3.4
    - mkdocs-get-deps >=0.2.0
    - pathspec >=0.11.1
    - packaging >=20.5
    - pyyaml >=5.1
    - pyyaml-env-tag >=0.1
    - watchdog >=2.0
  run_constrained:
    - babel >=2.9.0

test:
  requires:
    - pip
  imports:
    - mkdocs
    - mkdocs.commands
    - mkdocs.config
    - mkdocs.contrib
    - mkdocs.contrib.search
    - mkdocs.structure
    - mkdocs.themes
    - mkdocs.themes.mkdocs
    - mkdocs.themes.readthedocs
    - mkdocs.utils
  commands:
    - pip check
    - mkdocs --help

about:
  home: http://www.mkdocs.org
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Project documentation with Markdown

extra:
  recipe-maintainers:
    - dhirschfeld
    - ocefpaf
